// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddSession(arg1:string,arg2:string):Promise<main.State>;

export function AddSpacedSessions(arg1:string,arg2:string,arg3:Array<number>,arg4:boolean):Promise<main.State>;

export function AddSubject(arg1:string):Promise<main.State>;

export function AddTask(arg1:string,arg2:string,arg3:string):Promise<main.State>;

export function DeleteSession(arg1:string,arg2:string):Promise<main.State>;

export function DeleteSubject(arg1:string):Promise<main.State>;

export function DeleteTask(arg1:string):Promise<main.State>;

export function GetFocusSessions():Promise<Array<main.FocusSession>>;

export function GetState():Promise<main.State>;

export function GradeSession(arg1:string,arg2:string,arg3:string):Promise<main.State>;

export function RecordFocusSession(arg1:string,arg2:number):Promise<Array<main.FocusSession>>;

export function ReorderSubjects(arg1:Array<string>):Promise<main.State>;

export function ReorderTasks(arg1:Array<string>):Promise<main.State>;

export function RescheduleOverdueSessions():Promise<main.State>;

export function RescheduleSession(arg1:string,arg2:string,arg3:string):Promise<main.State>;

export function SetSubjectColor(arg1:string,arg2:string):Promise<main.State>;

export function SetTaskAdaptive(arg1:string,arg2:boolean):Promise<main.State>;

export function SetTaskArchived(arg1:string,arg2:boolean):Promise<main.State>;

export function SetTaskColor(arg1:string,arg2:string):Promise<main.State>;

export function SetTaskSubject(arg1:string,arg2:string):Promise<main.State>;

export function ToggleSession(arg1:string,arg2:string):Promise<main.State>;

export function UpdateSubject(arg1:string,arg2:string):Promise<main.State>;

export function UpdateTask(arg1:string,arg2:string,arg3:string,arg4:Array<string>):Promise<main.State>;
