// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddSession(arg1:string,arg2:string):Promise<Array<main.Topic>>;

export function AddSpacedSessions(arg1:string,arg2:string,arg3:Array<number>,arg4:boolean):Promise<Array<main.Topic>>;

export function AddTopic(arg1:string,arg2:string):Promise<Array<main.Topic>>;

export function DeleteSession(arg1:string,arg2:string):Promise<Array<main.Topic>>;

export function DeleteTopic(arg1:string):Promise<Array<main.Topic>>;

export function GetFocusSessions():Promise<Array<main.FocusSession>>;

export function GetTopics():Promise<Array<main.Topic>>;

export function GradeSession(arg1:string,arg2:string,arg3:string):Promise<Array<main.Topic>>;

export function RecordFocusSession(arg1:string,arg2:number):Promise<Array<main.FocusSession>>;

export function ReorderTopics(arg1:Array<string>):Promise<Array<main.Topic>>;

export function RescheduleOverdueSessions():Promise<Array<main.Topic>>;

export function RescheduleSession(arg1:string,arg2:string,arg3:string):Promise<Array<main.Topic>>;

export function SetTopicAdaptive(arg1:string,arg2:boolean):Promise<Array<main.Topic>>;

export function SetTopicArchived(arg1:string,arg2:boolean):Promise<Array<main.Topic>>;

export function SetTopicColor(arg1:string,arg2:string):Promise<Array<main.Topic>>;

export function ToggleSession(arg1:string,arg2:string):Promise<Array<main.Topic>>;

export function UpdateTopic(arg1:string,arg2:string,arg3:string,arg4:Array<string>):Promise<Array<main.Topic>>;
