// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddSession(arg1, arg2) {
  return window['go']['main']['App']['AddSession'](arg1, arg2);
}

export function AddSpacedSessions(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddSpacedSessions'](arg1, arg2, arg3, arg4);
}

export function AddSubject(arg1) {
  return window['go']['main']['App']['AddSubject'](arg1);
}

export function AddTask(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddTask'](arg1, arg2, arg3);
}

export function DeleteSession(arg1, arg2) {
  return window['go']['main']['App']['DeleteSession'](arg1, arg2);
}

export function DeleteSubject(arg1) {
  return window['go']['main']['App']['DeleteSubject'](arg1);
}

export function DeleteTask(arg1) {
  return window['go']['main']['App']['DeleteTask'](arg1);
}

export function GetFocusSessions() {
  return window['go']['main']['App']['GetFocusSessions']();
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function GradeSession(arg1, arg2, arg3) {
  return window['go']['main']['App']['GradeSession'](arg1, arg2, arg3);
}

export function RecordFocusSession(arg1, arg2) {
  return window['go']['main']['App']['RecordFocusSession'](arg1, arg2);
}

export function ReorderSubjects(arg1) {
  return window['go']['main']['App']['ReorderSubjects'](arg1);
}

export function ReorderTasks(arg1) {
  return window['go']['main']['App']['ReorderTasks'](arg1);
}

export function RescheduleOverdueSessions() {
  return window['go']['main']['App']['RescheduleOverdueSessions']();
}

export function RescheduleSession(arg1, arg2, arg3) {
  return window['go']['main']['App']['RescheduleSession'](arg1, arg2, arg3);
}

export function SetDailyGoalMinutes(arg1) {
  return window['go']['main']['App']['SetDailyGoalMinutes'](arg1);
}

export function SetSubjectColor(arg1, arg2) {
  return window['go']['main']['App']['SetSubjectColor'](arg1, arg2);
}

export function SetTaskAdaptive(arg1, arg2) {
  return window['go']['main']['App']['SetTaskAdaptive'](arg1, arg2);
}

export function SetTaskArchived(arg1, arg2) {
  return window['go']['main']['App']['SetTaskArchived'](arg1, arg2);
}

export function SetTaskColor(arg1, arg2) {
  return window['go']['main']['App']['SetTaskColor'](arg1, arg2);
}

export function SetTaskSubject(arg1, arg2) {
  return window['go']['main']['App']['SetTaskSubject'](arg1, arg2);
}

export function ToggleSession(arg1, arg2) {
  return window['go']['main']['App']['ToggleSession'](arg1, arg2);
}

export function UpdateSubject(arg1, arg2) {
  return window['go']['main']['App']['UpdateSubject'](arg1, arg2);
}

export function UpdateTask(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateTask'](arg1, arg2, arg3, arg4);
}
