// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddSession(arg1, arg2) {
  return window['go']['main']['App']['AddSession'](arg1, arg2);
}

export function AddSpacedSessions(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddSpacedSessions'](arg1, arg2, arg3, arg4);
}

export function AddTopic(arg1, arg2) {
  return window['go']['main']['App']['AddTopic'](arg1, arg2);
}

export function DeleteSession(arg1, arg2) {
  return window['go']['main']['App']['DeleteSession'](arg1, arg2);
}

export function DeleteTopic(arg1) {
  return window['go']['main']['App']['DeleteTopic'](arg1);
}

export function GetTopics() {
  return window['go']['main']['App']['GetTopics']();
}

export function GradeSession(arg1, arg2, arg3) {
  return window['go']['main']['App']['GradeSession'](arg1, arg2, arg3);
}

export function ReorderTopics(arg1) {
  return window['go']['main']['App']['ReorderTopics'](arg1);
}

export function RescheduleOverdueSessions() {
  return window['go']['main']['App']['RescheduleOverdueSessions']();
}

export function RescheduleSession(arg1, arg2, arg3) {
  return window['go']['main']['App']['RescheduleSession'](arg1, arg2, arg3);
}

export function SetTopicAdaptive(arg1, arg2) {
  return window['go']['main']['App']['SetTopicAdaptive'](arg1, arg2);
}

export function SetTopicArchived(arg1, arg2) {
  return window['go']['main']['App']['SetTopicArchived'](arg1, arg2);
}

export function SetTopicColor(arg1, arg2) {
  return window['go']['main']['App']['SetTopicColor'](arg1, arg2);
}

export function ToggleSession(arg1, arg2) {
  return window['go']['main']['App']['ToggleSession'](arg1, arg2);
}

export function UpdateTopic(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateTopic'](arg1, arg2, arg3, arg4);
}
